Use angular-translate to localize the website
HouraiTeahouse/houraiteahouse.net-frontend pull request #52
Opened 2017-01-08 09:36 UTC by james7132

Angular-translate implemented a number of localization requirements that we really needed:
* Asynchronous loading of localization data (currently just static files checked into this repo).
* Browser caching of localization data
* Storing localization preferences in HTML5 storage (gracefully falling back to cookies if the device/browser doesn't support it)
* Sanitization of localiztion data
* Utility translation filters and directives.

2017-01-08 23:20 UTC, gscoppino commented
The *very* first time you open the site in the browser, the value of "language" in the footer will be empty. It will remain empty until you manually change it.

2017-01-08 23:22 UTC, gscoppino commented
`/i18n/en.json` and `/i18n/en_US.json` are always loaded, even if the language is changed.

2017-01-08 23:27 UTC, gscoppino commented
On the `/project/fantasy-crescendo/characters` view, Wriggle's name is not loaded, it appears to be missing from the locale JSON.

2017-01-08 23:30 UTC, james7132 commented
The en/en_US.json is because English is specified as a fallback language, in the case that there is a translation that is not present in another language. A reasonable setting given that these are cached locally, and English will definitely have strings defined for it.

2017-01-08 23:34 UTC, gscoppino commented on src/i18n/de.json
> +      "MURASA": "Minamitsu Murasa"
Looks like you've got the family name and the given name in the opposite arrangement here (as compared to the other characters)

2017-01-08 23:34 UTC, gscoppino commented on src/i18n/de.json
> +  "LANGUAGE": "Langauge",
Typo in translation value

2017-01-08 23:34 UTC, gscoppino commented on src/index.html
> +          <span>{{"LANGUAGE"|translate}}: </span>
In other places you are using the `translate` directive instead of the `translate` filter. Let's do the same here?

2017-01-08 23:34 UTC, gscoppino commented on src/js/app.js
> +import 'angular-translate'
Semicolons to terminate these `import` statements

2017-01-08 23:34 UTC, gscoppino commented on src/partials/auth/login.html
> +          {{ "AUTH.REMEMBER_ME" | translate }}
Change to `<span translate>AUTH.REMEMBER_ME</span>` to use directive like in other places

2017-01-08 23:34 UTC, gscoppino commented on package.json
> +    "angular-translate": "^2.13.1",
Change these to use tilde ranges like the other dependencies we have. Our tilde ranges only accept patch updates while the NPM default ranges accept minor version updates as well. That's not necessarily a bad thing, but I personally opt (and opted here) for tilde ranges for safety (as the ecosystem can be brittle).

2017-01-08 23:34 UTC, gscoppino commented on package.json
> +    "watch-all-production": "npm run clean && run-p -l watch-html-production watch-css-production watch-js-production watch-other watch-fonts watch-images build-i18n",
Last run command should be `watch-i18n`, not `build-i18n`

2017-01-08 23:34 UTC, gscoppino commented on src/js/common/controllers.js
> +      console.log("translated");
Let's remove this debug statement (linter warning).

2017-01-08 23:34 UTC, gscoppino commented on src/i18n/de.json
> +  "PROJECTS": {
At the moment, we don't have localization for the project name / description. How we should handle these translations may not be straightforward.

2017-01-08 23:42 UTC, james7132 commented on src/i18n/de.json
> +      "MURASA": "Minamitsu Murasa"
Murasa is shorter: less typing and smaller files. =P

2017-01-08 23:47 UTC, james7132 commented on src/index.html
> +          <span>{{"LANGUAGE"|translate}}: </span>
It has the additional ": " that is independent of translation. Probably not the best idea to include it in the locale data since that is error prone.

2017-01-08 23:49 UTC, gscoppino commented
One thing I would suggest is passing the translate id directly to the `translate` directive, instead of having it as the node text value. When using the text value, you get a flash of untranslated translation id's before Angular replaces them with the translated values. I think it might be better if the node value empty or maybe something like `...`.

More info:
https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translate

2017-01-08 23:53 UTC, gscoppino commented on src/i18n/de.json
> +{
Have a translation for the website name on the home page

2017-01-08 23:53 UTC, gscoppino commented on src/index.html
> +          <span>{{"LANGUAGE"|translate}}: </span>
Got it, I agree not to put the colon in the translation

2017-01-09 00:00 UTC, gscoppino requested changes
Alright, that's everything I got. `angular-translate` seems to be very robust and well documented, and the implementation is good. Hopefully we can find a way to make the "flash of translation id's" issue on page load less jarring. We will need to figure out eventually how to handle translations of dynamic content such as project data (name/description, custom templates such as about/character details), but that can be tabled for now.

Good stuff @james7132 , this is a one big step forward :)

2017-01-09 01:52 UTC, gscoppino commented on src/i18n/de.json
> +  "PROJECTS": {
#54 created as a follow up for this.

2017-01-09 01:53 UTC, gscoppino approved these changes

2017-01-09 01:56 UTC, merged